### ISSUE TITLE
Any advice on GPIO pin mapping for the ATX control board?

### ISSUE THREAD

**Issue by RebelPhoton** [Yura80/pikvm-rock64#6]
Should we just connect the same pins than the official project, or should we remap those pins for different devices? Were is each pin configured? 
From [what I read](https://kaspars.net/blog/orange-pi-zero-gpio) the Orange Pi Zero pins are layed out similarly but the software/driver numbering is different? How does that work nowadays?

**Comment by RebelPhoton** [comment]
I'll answer my own question. 

TLDR: If using the same physical pins as a raspberry pi add this to /etc/kvmd/override.yaml
```
kvmd:
    atx:
        type: gpio
        power_led_pin: 18
        hdd_led_pin: 3
        power_switch_pin: 19
        reset_switch_pin: 0
```

Explanation:

The logical GPIO pin numbers change as indicated [here](https://kaspars.net/blog/orange-pi-zero-gpio) or [here](https://linux-sunxi.org/Xunlong_Orange_Pi_Zero#Expansion_Port). The syntax was copied from [here](https://github.com/pikvm/kvmd/blob/master/configs/kvmd/main/v0-hdmi-rpi3.yaml)
